version: '3.9'
services:
#  server:
#    image: 'my-server-container'
#    ports:
#      - "8080:8080"
  web:
    restart: unless-stopped   # restart policy
    logging:
      driver: none
    build:
      context: .
      dockerfile: Dockerfile
#    image: 'front-end-server'
    ports:
      - "80:3000"
    volumes:
      - .:/server/ui              # second param: map {current folder} to {/server/ui} in container
      - /server/ui/node_modules   # first param : do not map this inside the container
#  web-tests:    # run tests in separate container and watch
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    volumes:
#      - /server/ui/node_modules   # first param : do not map this inside the container
#      - .:/server/ui              # second param: map {current folder} to {/server/ui} in container
#    command: ["npm", "run", "test"]
